### ISSUE TITLE
好久能更新哦

### ISSUE THREAD

**Issue by Poker-J** [aliyun/alibabacloud-AliIMPInteractiveLive-Demo#1]
这个代码貌似不完善吧

**Comment by FernandoWei** [comment]
基本是完善，你是发现哪部分不完善？我找具体同学来修复

**Comment by Poker-J** [comment]
页面能否支持自定义呢  还是只提供一个进入方法呢?

**Comment by Poker-J** [comment]
有没有联系方式哦 我们项目需要这套直播插件

**Comment by FernandoWei** [comment]
有的，可以看下我们官网，https://help.aliyun.com/product/261167.html
