### ISSUE TITLE
观众端开始直播就崩溃，liveroom,CustomLiveRenderView加上这个后就会崩溃

### ISSUE THREAD

**Issue by Biekangdong** [aliyun/alibabacloud-AliIMPInteractiveLive-Demo#2]

**Comment by ytrjp** [comment]
Crash的日志可以发一下

**Comment by Biekangdong** [comment]
> 

试了，发现必须加arm64-v8a架构才可以，abiFilters  'armeabi-v7a','arm64-v8a'，项目中有其它三方的so库，这个怎样解决

**Comment by Biekangdong** [comment]
> > 
> 
> 试了，发现必须加arm64-v8a架构才可以，abiFilters 'armeabi-v7a','arm64-v8a'，项目中有其它三方的so库，这个怎样解决

原来只有abiFilters 'armeabi-v7a'

**Comment by Biekangdong** [comment]
我其它库必须有armeabi-v7a，直播又必须有arm64-v8a，所以我加了两个，但直播可以了，另一个功能就会报错，说没64的so库

**Comment by jason198609** [comment]
@Biekangdong 我遇到的情况跟你一样...

**Comment by aComputerGeek** [comment]
+1

**Comment by ytrjp** [comment]
def LATEST_VERSION = '1.8.0.20220613001'
升级到官网最新版本已经解决了这个问题
